project:
  type: website
  output-dir: docs
  preview:
    port: 4200

website:
  title: !expr read.dcf("DESCRIPTION")[1,"Title"]
  navbar:
    left:
    - text: Home
      href: index.qmd
    - text: Exploration
      href: examples-and-exercises.qmd  
    - text: Assignments
      menu:
        - text: Simulation and Computation
          href: simulation-and-computation.qmd
    right:
      - icon: github
        href: https://github.com/Bijans-Projects/design-and-analysis-of-experiments

format:
  html:
    theme:
    - cosmo
    - brand
    css: styles.css
    toc: true
